### ISSUE TITLE
request.forms.get

### ISSUE THREAD

**Issue by matijapretnar** [KrumJ12/Vodenje-lokala#1]
V funkciji `uredi_osebo_submit` uporabljata `request.forms.get('xxx')` namesto `request.forms.xxx`. Če sta to pobrala od mene, se opravičujem. Druga varianta je boljša, ker ustrezno poskrbi za Unicode (nekateri vajini kolegi so imeli težave s tem).

**Comment by KrumJ12** [comment]
Ta funkcija je bila pobrana iz vašega urnika in še ni bila deležna popravkov (še ime ni bilo zamenjano), pri ostalih funkcijah, pa je klic pravilen (request.forms.xxx). Težavo z Unicode sva imela tudi midva, na zadnjih predavanjih.

Hvala za opozorilo :)
